# Generated by Django 5.1.4 on 2024-12-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetail',
        ),
    ]
